name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: What problem does it solve for you? What does the command/output look like in your head?
    validations:
      required: true
